name: hydrated
description: "Hydration Reminder App for you to stay hydrated!"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Data model
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Utilities
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter_screenutil: ^5.9.0

  # Route
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7

  # Generator
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 200
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 600
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          style: italic
